### ISSUE TITLE
Top-level directory in zip file should be "WonderRep"

### ISSUE THREAD

**Issue by SpareSimian** [nawglan/wonder-rep#6]
The latest release zip file, 2.1.15, has the top-level directory "wonder-rep-2.1.15", which WoW doesn't recognize. Renaming it to "WonderRep" allows WoW to find the addon. (I downloaded it from GitHub and unzipped it into my Addons directory.)

**Comment by rellis6** [comment]
Oops! I think I fixed it, thanks for letting me know so fast!
